---
title: "Graficaci칩n en ggplot2 y quarto"
author: Miriana Guerrero Dinarte
format:
  html:
    toc: true
    toc_float: true
    lang: Es
---

# Introducci칩n

Este documento presenta un conjutno de visualizaciones de datos elaborados con paquetes de lenguaje R como ggplot2, plotly y DT.

# Carga de bibliotecas

```{r}
#| label: carga-biblioteca
#| warning: false
library(tidyverse)
library(plotly)
library(DT)
library(gapminder)
```

# Carga de datos

## mpg

```{r}
#| label: carga-datos-mpg
#| warning: false
#| code-fold: true

# Tabla de datos de mpg
mpg |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Diamonds

```{r}
#| label: carga-datos-diamonds
#| warning: false
#| code-fold: true
# Tabla de datos de diamonds
diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## gapminder

```{r}
#| label: carga-datos-gapminder
#| warning: false
#| code-fold: true
# Tabla de datos de gapminder
gapminder |>
  filter(year == 2007) |> # filtro para el a침o 2007
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Casos de COVID-19 en Costa Rica

```{r}
#| label: carga-datos-covid
#| warning: false
#| code-fold: true
# Carga del archivo CSV de entrada en un dataframe
# con la funci칩n read_delim() de readr
covid_general <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/ministerio-salud/covid/05_30_22_CSV_GENERAL.csv",
    col_select = c(
      "FECHA",
      "positivos",
      "activos",
      "RECUPERADOS",
      "fallecidos",
      "nue_posi",
      "nue_falleci",
      "salon",
      "UCI"
    )
  )

# Cambio de nombre de columnas
covid_general <-
  covid_general |>
  rename(
    fecha = FECHA,
    recuperados = RECUPERADOS,
    nuevos_positivos = nue_posi,
    nuevos_fallecidos = nue_falleci,
    uci = UCI
  )

# Cambio de tipo de datos de la columna fecha, de str a date
covid_general <-
  covid_general |>
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))

# Despliegue de datos
covid_general |>
  datatable(
    options = list(
      pageLength = 25,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Delitos

```{r}
#| label: carga-datos-delitos
#| warning: false
#| code-fold: true

# Carga de datos
delitos_2022 <-
  read_delim(
    file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/oij/estadisticas-policiales/estadisticaspoliciales2022.csv"
  )

# Tabla de datos
delitos_2022 |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```
